#!/bin/bash
# vim: set ts=4 sts=4 sw=4 et:

die() {
    echo "$@" >&2
    exit 1
}

[[ -n "$LOGSTASH_HOSTS" ]] || die "LOGSTASH_HOSTS environment variable not specified"

# If we are running under Rancher, then we should use the
# hostname of the cluster host running this service to make
# sure that the registry file has a unique name
RANCHER_HOSTNAME="$(curl -fsSL 'http://rancher-metadata/latest/self/host/hostname')"
if [[ -n "$RANCHER_HOSTNAME" ]]; then
    echo "Detected that you are running within Rancher host: $RANCHER_HOSTNAME"
    export DOCKLOGBEAT_REGISTRY_FILE_NAME="${DOCKLOGBEAT_REGISTRY_FILE_NAME:-/var/lib/filebeat/registry-$RANCHER_HOSTNAME}"
fi

# set registry filename if not overriden
export DOCKLOGBEAT_REGISTRY_FILE_NAME="${DOCKLOGBEAT_REGISTRY_FILE_NAME:-/var/lib/filebeat/registry}"

# provide defaults for label key and value used to filter containers
export DOCKLOGBEAT_LABEL_KEY="${DOCKLOGBEAT_LABEL_KEY:-docklogbeat}"
export DOCKLOGBEAT_LABEL_VALUE="${DOCKLOGBEAT_LABEL_VALUE:-true}"

# create dummy log file so that filebeat always has at least one prospector available
mkdir -p /var/log
touch /var/log/dummy

exec /usr/bin/supervisord -n -c /etc/supervisord.conf
